# Data Inspection — Motor Vehicle Collisions with KSI Data

## Objective

This notebook performs the initial inspection of the raw dataset for CST8504 Assignment 1.

The goals of this notebook are to:

- Load the raw dataset without modifying it.
- Inspect the dataset shape.
- Review column names and data types.
- Examine summary statistics.
- Identify missing values.
- Check for duplicate records.
- Review the proposed target variable.
- Identify possible identifier, leakage, and candidate predictor columns.

All cleaning and transformation steps will be performed later in code so the raw dataset remains unchanged.

### Set Up the Project Path

This step imports the required libraries and identifies the project root directory. A relative path is then created for the raw collision dataset so the notebook can locate the file consistently whether it is run from the project root or from the `notebooks` folder. The file-existence check confirms that the raw dataset is available before loading it.

In [1]:
from pathlib import Path
import pandas as pd

# Locate the project root
project_root = Path.cwd()

# If the notebook is running from the notebooks folder,
# move one level up to the project root
if project_root.name == "notebooks":
    project_root = project_root.parent

# Path to the untouched raw dataset
data_path = (
    project_root
    / "data"
    / "raw"
    / "Motor Vehicle Collisions with KSI Data - 4326.csv"
)

print("Dataset path:", data_path)
print("File exists:", data_path.exists())

Dataset path: c:\Git\AI Software Development\CST8504_Applying_AI_Technics\assignment1_prediction_dashboard\data\raw\Motor Vehicle Collisions with KSI Data - 4326.csv
File exists: True

### Load the Raw Dataset

This step loads the untouched collision dataset into a pandas DataFrame and checks its dimensions. The number of rows and columns provides an initial understanding of the dataset size before any cleaning, filtering, or transformation is applied.

In [2]:
# Load the raw dataset into a pandas DataFrame
df = pd.read_csv(data_path)

# Display the dataset dimensions
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])
print("Dataset shape:", df.shape)

Number of rows: 20771
Number of columns: 50
Dataset shape: (20771, 50)

### Review the Dataset Columns

This step lists every column in the raw dataset together with its position. Reviewing the available fields helps identify potential predictors, identifiers, target-related variables, and columns that may require further investigation during preprocessing.

In [3]:
# Display all column names with their position
for index, column in enumerate(df.columns, start=1):
    print(f"{index:2}. {column}")

 1. _id
 2. collision_id
 3. accdate
 4. stname1
 5. stname2
 6. stname3
 7. per_inv
 8. acclass
 9. accloc
10. traffictl
11. impactype
12. visible
13. light
14. rdsfcond
15. road_class
16. failtorem
17. longitude
18. latitude
19. veh_no
20. vehtype
21. initdir
22. per_no
23. invage
24. injury
25. safequip
26. drivact
27. drivcond
28. pedact
29. pedcond
30. manoeuvre
31. pedtype
32. cyclistype
33. cycact
34. cyccond
35. road_user
36. fatal_no
37. wardname
38. division
39. neighbourhood
40. aggressive
41. distracted
42. cyclist
43. motorcyclist
44. other_micromobility
45. older_adult
46. pedestrian
47. red_light
48. school_child
49. heavy_truck
50. geometry

### Inspect Data Types and Non-Null Values

This step uses `DataFrame.info()` to review the data type of each column and the number of non-null values available. This helps identify numeric, categorical, and text-based fields while also revealing columns that contain missing data and may require preprocessing.

In [4]:
# Display column data types and non-null counts
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20771 entries, 0 to 20770
Data columns (total 50 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   _id                  20771 non-null  int64
 1   collision_id         20771 non-null  object
 2   accdate              20771 non-null  object
 3   stname1              20771 non-null  object
 4   stname2              18998 non-null  object
 5   stname3              4848 non-null   object
 6   per_inv              20771 non-null  int64
 7   acclass              20770 non-null  object
 8   accloc               15315 non-null  object
 9   traffictl            20594 non-null  object
 10  impactype            20740 non-null  object
 11  visible              20698 non-null  object
 12  light                20718 non-null  object
 13  rdsfcond             20688 non-null  object
 14  road_class           19888 non-null  object
 15  failtorem            20771 non-null  bool
 16  longitude            20768 non-null  float64
 17  latitude             20768 non-null  float64
 18  veh_no               20271 non-null  float64
 19  vehtype              11932 non-null  object
 20  initdir              14900 non-null  object
 21  per_no               20770 non-null  float64
 22  invage               18147 non-null  float64
 23  injury               11072 non-null  object
 24  safequip             19313 non-null  object
 25  drivact              10681 non-null  object
 26  drivcond             10698 non-null  object
 27  pedact               3617 non-null   object
 28  pedcond              3610 non-null   object
 29  manoeuvre            12095 non-null  object
 30  pedtype              3553 non-null   object
 31  cyclistype           889 non-null    object
 32  cycact               899 non-null    object
 33  cyccond              896 non-null    object
 34  road_user            20771 non-null  object
 35  fatal_no             1104 non-null   float64
 36  wardname             20649 non-null  object
 37  division             20705 non-null  object
 38  neighbourhood        20620 non-null  object
 39  aggressive           20771 non-null  bool
 40  distracted           20771 non-null  bool
 41  cyclist              20771 non-null  bool
 42  motorcyclist         20771 non-null  bool
 43  other_micromobility  20771 non-null  bool
 44  older_adult          20771 non-null  bool
 45  pedestrian           20771 non-null  bool
 46  red_light            20771 non-null  bool
 47  school_child         20771 non-null  bool
 48  heavy_truck          20771 non-null  bool
 49  geometry             20768 non-null  object
dtypes: bool(11), float64(6), int64(2), object(31)
memory usage: 6.4+ MB

### Identify Missing Values

This step calculates the number and percentage of missing values in each column. The results are sorted from highest to lowest missingness so that fields requiring cleaning, imputation, or possible removal can be identified more easily.

In [5]:
# Calculate missing-value counts and percentages for each column
missing_values = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing Percentage": (df.isnull().sum() / len(df) * 100).round(2)
})

# Sort from the highest to the lowest percentage of missing values
missing_values = missing_values.sort_values(
    by="Missing Percentage",
    ascending=False
)

missing_values

                     Missing Count  Missing Percentage
cyclistype                   19882               95.72
cyccond                      19875               95.69
cycact                       19872               95.67
fatal_no                     19667               94.68
pedtype                      17218               82.89
pedcond                      17161               82.62
pedact                       17154               82.59
stname3                      15923               76.66
drivact                      10090               48.58
drivcond                     10073               48.50
injury                        9699               46.69
vehtype                       8839               42.55
manoeuvre                     8676               41.77
initdir                       5871               28.27
accloc                        5456               26.27
invage                        2624               12.63
stname2                       1773                8.54
safequip                      1458                7.02
road_class                     883                4.25
veh_no                         500                2.41
traffictl                      177                0.85
neighbourhood                  151                0.73
wardname                       122                0.59
rdsfcond                        83                0.40
visible                         73                0.35
division                        66                0.32
light                           53                0.26
impactype                       31                0.15
longitude                        3                0.01
geometry                         3                0.01
latitude                         3                0.01
accdate                          0                0.00
_id                              0                0.00
collision_id                     0                0.00
failtorem                        0                0.00
stname1                          0                0.00
acclass                          1                0.00
per_inv                          0                0.00
per_no                           1                0.00
road_user                        0                0.00
distracted                       0                0.00
aggressive                       0                0.00
cyclist                          0                0.00
motorcyclist                     0                0.00
older_adult                      0                0.00
other_micromobility              0                0.00
pedestrian                       0                0.00
red_light                        0                0.00
school_child                     0                0.00
heavy_truck                      0                0.00

### Review Numeric Summary Statistics

This step summarizes the numeric columns using descriptive statistics such as count, mean, standard deviation, minimum, maximum, and quartiles. Reviewing these values helps identify unusual ranges, potential outliers, and variables that may require additional preprocessing before modelling.

In [6]:
# Display summary statistics for numeric columns
numeric_summary = df.describe()

numeric_summary

,_id,per_inv,longitude,latitude,veh_no,per_no,invage,fatal_no
count,20771.000000,20771.000000,20768.000000,20768.000000,20271.000000,20770.000000,18147.000000,1104.000000
mean,10386.000000,3.401329,-79.396878,43.710019,1.481871,2.229610,42.597179,27.933877
std,5996.215556,2.032979,0.104829,0.056086,0.792637,1.541472,28.495841,17.102437
min,1.000000,1.000000,-79.638391,43.588646,0.000000,1.000000,0.000000,1.000000
25%,5193.500000,2.000000,-79.472805,43.661944,1.000000,1.000000,27.000000,14.000000
50%,10386.000000,3.000000,-79.397671,43.702138,1.000000,2.000000,41.000000,27.000000
75%,15578.500000,4.000000,-79.318442,43.755476,2.000000,3.000000,56.000000,40.000000
max,20771.000000,18.000000,-79.122975,43.855444,10.000000,19.000000,2023.000000,78.000000

## Feature Audit

The feature audit combines the dataset dictionary with statistics calculated from the raw dataset.

Each attribute is reviewed according to:

- whether it describes the collision event or an individual involved person/vehicle;
- its pandas data type;
- missing values;
- number of unique values;
- its possible role in the machine learning project;
- possible issues such as identifiers, target leakage, high missingness, or the need for feature engineering.

The classifications in this table are preliminary and may change after exploratory data analysis.

### Classify Columns by Data Level

The dataset contains both collision-level attributes and person- or vehicle-level attributes. This step separates the columns into event-level and involved-level groups based on the official dataset dictionary. This distinction is important because the final modelling dataset should contain one record per collision rather than multiple records for each person or vehicle involved.

In [7]:
# Attribute level based on the official dataset dictionary

event_level_columns = [
    "collision_id",
    "accdate",
    "stname1",
    "stname2",
    "stname3",
    "per_inv",
    "acclass",
    "accloc",
    "traffictl",
    "impactype",
    "visible",
    "light",
    "rdsfcond",
    "road_class",
    "failtorem",
    "longitude",
    "latitude",
    "wardname",
    "division",
    "neighbourhood",
    "aggressive",
    "distracted",
    "cyclist",
    "motorcyclist",
    "other_micromobility",
    "older_adult",
    "pedestrian",
    "red_light",
    "school_child",
    "heavy_truck"
]

involved_level_columns = [
    "veh_no",
    "vehtype",
    "initdir",
    "per_no",
    "invage",
    "injury",
    "safequip",
    "drivact",
    "drivcond",
    "pedact",
    "pedcond",
    "manoeuvre",
    "pedtype",
    "cyclistype",
    "cycact",
    "cyccond",
    "road_user",
    "fatal_no"
]

### Build the Feature Audit Table

This step creates a structured audit of the dataset features by recording each column's data level, data type, number of unique values, missing-value count, and missing-value percentage. The audit helps identify identifiers, high-missingness columns, and variables that may require further review before the collision-level dataset is created.

In [8]:
def get_level(column):
    if column == "_id":
        return "Row identifier"
    elif column in event_level_columns:
        return "Event"
    elif column in involved_level_columns:
        return "Involved"
    else:
        return "Unknown / Review"


feature_audit = pd.DataFrame({
    "Column": df.columns,
    "Level": [get_level(column) for column in df.columns],
    "Data Type": [str(df[column].dtype) for column in df.columns],
    "Missing Count": [df[column].isnull().sum() for column in df.columns],
    "Missing %": [
        round(df[column].isnull().mean() * 100, 2)
        for column in df.columns
    ],
    "Unique Values": [df[column].nunique(dropna=True) for column in df.columns]
})

feature_audit

,Column,Level,Data Type,Missing Count,Missing %,Unique Values
0,_id,Row identifier,int64,0,0.00,20771
1,collision_id,Event,object,0,0.00,7620
2,accdate,Event,object,0,0.00,7597
3,stname1,Event,object,0,0.00,2067
4,stname2,Event,object,1773,8.54,2962
5,stname3,Event,object,15923,76.66,594
6,per_inv,Event,int64,0,0.00,17
7,acclass,Event,object,1,0.00,3
8,accloc,Event,object,5456,26.27,17
9,traffictl,Event,object,177,0.85,14
10,impactype,Event,object,31,0.15,13
11,visible,Event,object,73,0.35,9
12,light,Event,object,53,0.26,9
13,rdsfcond,Event,object,83,0.40,9
14,road_class,Event,object,883,4.25,12
15,failtorem,Event,bool,0,0.00,2
16,longitude,Event,float64,3,0.01,6941
17,latitude,Event,float64,3,0.01,6941
18,veh_no,Involved,float64,500,2.41,11
19,vehtype,Involved,object,8839,42.55,36
20,initdir,Involved,object,5871,28.27,5
21,per_no,Involved,float64,1,0.00,19
22,invage,Involved,float64,2624,12.63,101
23,injury,Involved,object,9699,46.69,4
24,safequip,Involved,object,1458,7.02,12
25,drivact,Involved,object,10090,48.58,14
26,drivcond,Involved,object,10073,48.50,17
27,pedact,Involved,object,17154,82.59,17
28,pedcond,Involved,object,17161,82.62,18
29,manoeuvre,Involved,object,8676,41.77,18
30,pedtype,Involved,object,17218,82.89,16
31,cyclistype,Involved,object,19882,95.72,30
32,cycact,Involved,object,19872,95.67,12
33,cyccond,Involved,object,19875,95.69,11
34,road_user,Involved,object,0,0.00,8
35,fatal_no,Involved,float64,19667,94.68,78
36,wardname,Event,object,122,0.59,25
37,division,Event,object,66,0.32,16
38,neighbourhood,Event,object,151,0.73,158
39,aggressive,Event,bool,0,0.00,2
40,distracted,Event,bool,0,0.00,2
41,cyclist,Event,bool,0,0.00,2
42,motorcyclist,Event,bool,0,0.00,2
43,other_micromobility,Event,bool,0,0.00,2
44,older_adult,Event,bool,0,0.00,2
45,pedestrian,Event,bool,0,0.00,2
46,red_light,Event,bool,0,0.00,2
47,school_child,Event,bool,0,0.00,2
48,heavy_truck,Event,bool,0,0.00,2
49,geometry,Unknown / Review,object,3,0.01,6941

### Check for Exact Duplicate Records

This step checks whether the raw dataset contains any rows that are completely duplicated across all columns. Identifying duplicate records is an important data-quality check because duplicates could distort counts, distributions, and later model training if they are not addressed.

In [12]:
# Check for exact duplicate rows
duplicate_count = df.duplicated().sum()

print("Number of exact duplicate rows:", duplicate_count)

Number of exact duplicate rows: 0

### Inspect Records per Collision

The raw dataset can contain multiple rows for the same collision because individual people or vehicles involved may be recorded separately. This step counts the number of records associated with each `collision_id` to confirm that the raw data is not yet at a one-row-per-collision level.

In [13]:
# Inspect the number of records associated with each collision
records_per_collision = df["collision_id"].value_counts()

print("Number of unique collisions:", records_per_collision.size)
print("Minimum records per collision:", records_per_collision.min())
print("Maximum records per collision:", records_per_collision.max())
print("Average records per collision:", round(records_per_collision.mean(), 2))

Number of unique collisions: 7620
Minimum records per collision: 1
Maximum records per collision: 19
Average records per collision: 2.73

### Inspect the Target Variable Distribution

This step examines the frequency of each value in `acclass`, the proposed target variable for the classification task. Reviewing the target distribution helps identify the available outcome classes and reveals whether the dataset is imbalanced before any filtering or modelling is performed.

In [14]:
# Inspect the distribution of the proposed target variable
target_counts = df["acclass"].value_counts(dropna=False)

target_counts

acclass
Non-Fatal Injury        17812
Fatal Injury             2940
Property Damage Only       18
NaN                         1
Name: count, dtype: int64

### Validate Target Consistency Within Collisions

Because the raw dataset can contain multiple rows for the same collision, this step checks whether every record sharing the same `collision_id` also has the same `acclass` value. Confirming target consistency ensures that each collision can be assigned one reliable outcome before the data is reduced to a single row per collision.

In [15]:
# Check whether each collision has only one acclass value
acclass_per_collision = (
    df.groupby("collision_id")["acclass"]
      .nunique(dropna=False)
)

inconsistent_collisions = (acclass_per_collision > 1).sum()

print(
    "Collisions with more than one acclass value:",
    inconsistent_collisions
)

Collisions with more than one acclass value: 0

### Create a Collision-Level Target Summary

This step reduces the target information to one `acclass` value per `collision_id`. The resulting collision-level summary is used to review the true class distribution without counting the same collision multiple times because of person- or vehicle-level records.

In [16]:
# Create one target value per collision
collision_target = (
    df[["collision_id", "acclass"]]
    .drop_duplicates(subset="collision_id")
)

# Display collision-level target distribution
collision_target["acclass"].value_counts(dropna=False)

acclass
Non-Fatal Injury        6543
Fatal Injury            1068
Property Damage Only       8
NaN                        1
Name: count, dtype: int64

### Target Distribution Observation

The proposed target variable, `acclass`, is consistent within each `collision_id`.

At the collision level, the dataset contains:

- 6,543 Non-Fatal Injury collisions
- 1,068 Fatal Injury collisions
- 8 Property Damage Only collisions
- 1 missing target value

Because the proposed machine learning task is binary classification of Fatal Injury versus Non-Fatal Injury, the Property Damage Only and missing target records will be reviewed for exclusion during preprocessing.

### Create the Collision-Level Dataset

The raw dataset contains multiple involved-person records for some collisions. This step keeps only event-level attributes and removes repeated event information so that each `collision_id` is represented by a single collision-level record for further preprocessing and modelling.

In [17]:
# Create a collision-level dataset using event-level attributes only
collision_df = (
    df[event_level_columns]
    .drop_duplicates()
    .reset_index(drop=True)
)

print("Collision-level shape:", collision_df.shape)
print("Unique collision IDs:", collision_df["collision_id"].nunique())
print(
    "Repeated collision IDs:",
    collision_df["collision_id"].duplicated().sum()
)

Collision-level shape: (7620, 30)
Unique collision IDs: 7620
Repeated collision IDs: 0

### Reassess Missing Values at the Collision Level

After reducing the raw data to one record per collision, this step recalculates the number and percentage of missing values for each event-level feature. This provides a more accurate view of missingness in the dataset that will actually be used for preprocessing and modelling.

In [18]:
# Inspect missing values in the collision-level dataset
collision_missing = pd.DataFrame({
    "Missing Count": collision_df.isnull().sum(),
    "Missing %": (
        collision_df.isnull().sum() / len(collision_df) * 100
    ).round(2)
})

collision_missing = collision_missing.sort_values(
    by="Missing %",
    ascending=False
)

collision_missing

                     Missing Count  Missing %
stname3                       5635      73.95
accloc                        1841      24.16
stname2                        692       9.08
road_class                     327       4.29
traffictl                       75       0.98
neighbourhood                   45       0.59
wardname                        38       0.50
rdsfcond                        38       0.50
visible                         36       0.47
light                           26       0.34
division                        25       0.33
impactype                       11       0.14
longitude                        1       0.01
acclass                          1       0.01
latitude                         1       0.01
collision_id                     0       0.00
stname1                          0       0.00
per_inv                          0       0.00
accdate                          0       0.00
failtorem                        0       0.00
aggressive                       0       0.00
distracted                       0       0.00
cyclist                          0       0.00
motorcyclist                     0       0.00
other_micromobility              0       0.00
older_adult                      0       0.00
pedestrian                       0       0.00
red_light                        0       0.00
school_child                     0       0.00
heavy_truck                      0       0.00

### Handle Missing Values

This step creates a preprocessing copy of the collision-level dataset and applies several missing-value treatments. The high-missingness `stname3` column is removed, rows with missing target values or geographic coordinates are dropped, missing `accloc` values are assigned an `"Unknown"` category, and the remaining categorical missing values are filled with the most frequent value (mode) in each column. The final check confirms the resulting dataset shape and verifies that missing values have been addressed.

In [19]:
# Create a copy for preprocessing
processed_df = collision_df.copy()

# 1. Drop stname3 because it has very high missingness
processed_df = processed_df.drop(columns=["stname3"])

# 2. Drop rows with a missing target
processed_df = processed_df.dropna(subset=["acclass"])

# 3. Drop rows with missing geographic coordinates
processed_df = processed_df.dropna(
    subset=["longitude", "latitude"]
)

# 4. Treat missing accloc values as their own category
processed_df["accloc"] = processed_df["accloc"].fillna("Unknown")

# 5. Fill remaining categorical missing values with the mode
categorical_columns = [
    "stname2",
    "road_class",
    "traffictl",
    "neighbourhood",
    "wardname",
    "rdsfcond",
    "visible",
    "light",
    "division",
    "impactype"
]

for column in categorical_columns:
    processed_df[column] = processed_df[column].fillna(
        processed_df[column].mode()[0]
    )

print("Shape after missing-value handling:", processed_df.shape)
print()
print("Remaining missing values:")
print(processed_df.isnull().sum().sort_values(ascending=False).head(10))

Shape after missing-value handling: (7618, 29)

Remaining missing values:
collision_id    0
accdate         0
stname1         0
stname2         0
per_inv         0
acclass         0
accloc          0
traffictl       0
impactype       0
visible         0
dtype: int64

### Identify Numeric Features for Outlier Analysis

This step selects the numeric columns from the cleaned collision-level dataset. These variables are reviewed separately because numeric features can contain unusually large or small values that may need to be investigated before modelling.

In [20]:
# Inspect numeric columns in the processed collision-level dataset
numeric_columns = processed_df.select_dtypes(
    include=["int64", "float64"]
).columns

numeric_columns

Index(['per_inv', 'longitude', 'latitude'], dtype='object')

### Detect Potential Numeric Outliers

This step uses the interquartile range (IQR) method to identify unusually low or high values in the numeric features. Potential outliers are reviewed rather than removed automatically because some extreme values may represent valid collision characteristics instead of data errors.

In [21]:
# Detect outliers using the IQR method
for column in numeric_columns:
    Q1 = processed_df[column].quantile(0.25)
    Q3 = processed_df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = processed_df[
        (processed_df[column] < lower_bound) |
        (processed_df[column] > upper_bound)
    ]

    print(f"{column}")
    print(f"Lower bound: {lower_bound:.4f}")
    print(f"Upper bound: {upper_bound:.4f}")
    print(f"Number of potential outliers: {len(outliers)}")
    print()

per_inv
Lower bound: 0.5000
Upper bound: 4.5000
Number of potential outliers: 680

longitude
Lower bound: -79.7018
Upper bound: -79.0912
Number of potential outliers: 0

latitude
Lower bound: 43.5212
Upper bound: 43.8948
Number of potential outliers: 0

### Review the `per_inv` Outliers

The IQR method flagged unusually high values in `per_inv`, which represents the number of people involved in a collision. This step examines the frequency of each `per_inv` value so the flagged observations can be judged in context before deciding whether they should be removed or retained.

In [22]:
# Inspect the distribution of people involved per collision
per_inv_distribution = (
    processed_df["per_inv"]
    .value_counts()
    .sort_index()
)

per_inv_distribution

per_inv
1      537
2     4067
3     1632
4      702
5      309
6      202
7       82
8       36
9       21
10      11
11       6
12       3
13       3
14       2
15       2
16       1
18       2
Name: count, dtype: int64

### Outlier Handling

The IQR method identified 680 potential outliers in `per_inv`, representing collisions involving five or more people.

These observations were retained because `per_inv` is a count of the number of people involved in a collision, and the higher values are plausible rather than obvious data-entry errors.

No potential outliers were detected for `longitude` or `latitude` using the IQR method.

### Create the Binary Classification Dataset

This step keeps only the two injury classes used for the prediction task: `Fatal Injury` and `Non-Fatal Injury`. A new binary target variable is then created, where `1` represents a Fatal Injury collision and `0` represents a Non-Fatal Injury collision. The resulting class distribution is reviewed to confirm the final modelling dataset.

In [23]:
# Keep only the two classes used for binary classification
model_df = processed_df[
    processed_df["acclass"].isin([
        "Fatal Injury",
        "Non-Fatal Injury"
    ])
].copy()

# Create a binary target:
# 1 = Fatal Injury
# 0 = Non-Fatal Injury
model_df["target"] = model_df["acclass"].map({
    "Fatal Injury": 1,
    "Non-Fatal Injury": 0
})

print("Modeling dataset shape:", model_df.shape)
print()
print("Binary target distribution:")
print(model_df["target"].value_counts())

Modeling dataset shape: (7610, 30)

Binary target distribution:
target
0    6543
1    1067
Name: count, dtype: int64

### Split the Data into Training, Validation, and Test Sets

This step separates the predictors from the binary target and divides the dataset into training, validation, and test sets using a 70/15/15 split. Stratified sampling is applied so that the Fatal and Non-Fatal Injury class proportions remain consistent across all three subsets, while a fixed random state ensures reproducible results.

In [24]:
from sklearn.model_selection import train_test_split
# Separate predictors and target
X = model_df.drop(columns=["target", "acclass"])
y = model_df["target"]

# First split: 70% training, 30% temporary
X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

# Second split: divide temporary data equally
# 15% validation and 15% test
X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.50,
    random_state=42,
    stratify=y_temp
)

print("Training set:", X_train.shape, y_train.shape)
print("Validation set:", X_val.shape, y_val.shape)
print("Test set:", X_test.shape, y_test.shape)

Training set: (5327, 28) (5327,)
Validation set: (1141, 28) (1141,)
Test set: (1142, 28) (1142,)

### Verify Class Distribution Across Data Splits

This step checks the proportion of Fatal and Non-Fatal Injury cases in the training, validation, and test sets. Because stratified sampling was used, the class distribution should remain approximately the same in all three subsets.

In [25]:
print("Training target distribution:")
print(y_train.value_counts(normalize=True).round(3))

print("\nValidation target distribution:")
print(y_val.value_counts(normalize=True).round(3))

print("\nTest target distribution:")
print(y_test.value_counts(normalize=True).round(3))

Training target distribution:
target
0    0.86
1    0.14
Name: proportion, dtype: float64

Validation target distribution:
target
0    0.86
1    0.14
Name: proportion, dtype: float64

Test target distribution:
target
0    0.86
1    0.14
Name: proportion, dtype: float64

### Scale the Numeric Features

This step standardizes the numeric predictors `per_inv`, `longitude`, and `latitude` using `StandardScaler`. The scaler is fitted only on the training data and then applied to the validation and test sets to prevent information from the validation or test data from leaking into the training process.

In [26]:
from sklearn.preprocessing import StandardScaler

# Create copies so the original splits remain unchanged
X_train_scaled = X_train.copy()
X_val_scaled = X_val.copy()
X_test_scaled = X_test.copy()

# Numeric columns to scale
numeric_features = ["per_inv", "longitude", "latitude"]

# Create and fit the scaler using training data only
scaler = StandardScaler()

X_train_scaled[numeric_features] = scaler.fit_transform(
    X_train[numeric_features]
)

# Apply the same scaler to validation and test data
X_val_scaled[numeric_features] = scaler.transform(
    X_val[numeric_features]
)

X_test_scaled[numeric_features] = scaler.transform(
    X_test[numeric_features]
)

print("Scaled training numeric features:")
print(X_train_scaled[numeric_features].describe().round(3))

Scaled training numeric features:
        per_inv  longitude  latitude
count  5327.000   5327.000  5327.000
mean     -0.000     -0.000    -0.000
std       1.000      1.000     1.000
min      -1.222     -2.288    -2.151
25%      -0.499     -0.727    -0.849
50%      -0.499     -0.012    -0.154
75%       0.224      0.728     0.821
max      11.069      2.616     2.630

### Save the Processed Dataset

This step saves the final cleaned collision-level dataset as `processed_collisions.csv` in the project's `data/processed/` folder. Saving the processed data creates a reusable model-ready file so later notebooks and application components can work from the same cleaned dataset without repeating the raw-data preprocessing steps.

In [27]:
# Create the processed-data directory path
processed_data_path = (
    project_root
    / "data"
    / "processed"
    / "processed_collisions.csv"
)

# Save the cleaned modeling dataset
model_df.to_csv(
    processed_data_path,
    index=False
)

print("Processed dataset saved to:")
print(processed_data_path)

print("\nSaved dataset shape:")
print(model_df.shape)

Processed dataset saved to:
c:\Git\AI Software Development\CST8504_Applying_AI_Technics\assignment1_prediction_dashboard\data\processed\processed_collisions.csv

Saved dataset shape:
(7610, 30)

### Verify the Saved Processed Dataset

This final check reloads the saved processed CSV file and verifies its shape, missing-value count, and target distribution. Reloading the file confirms that the exported dataset was written correctly and is ready to be used consistently by the EDA, modelling, and dashboard components.

In [28]:
# Verify the saved processed dataset
saved_df = pd.read_csv(processed_data_path)

print("File exists:", processed_data_path.exists())
print("Reloaded dataset shape:", saved_df.shape)
print("Remaining missing values:", saved_df.isnull().sum().sum())

File exists: True
Reloaded dataset shape: (7610, 30)
Remaining missing values: 0